// Creative / illustrated storyboard templates.
// See product.js header for the `c` context contract.

const tiny_workers_miniature = (c) => `A professional Pixar-style 3D animated storyboard presentation sheet, vertical layout. At the top header, a prominent brand logo on the left, a bold title 'STORYBOARD - Tiny Workers' with the scene description in center with 'PART ${c.pageNum}', a widescreen Pixar 3D illustration of a workshop or themed studio scene on the right, and metadata badges showing 'DURASI ${c.durasiLabel}', 'ASPECT RATIO ${c.rasioLabel}', 'GAYA Pixar-style 3D Animation'. The main content is a structured 2x3 (6-panel) grid layout displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each panel displays a widescreen 3D animated scene showing tiny toy workers (Lego/Pixar style) in yellow builder helmets crafting miniature objects, a dark-green square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at the top-left, a duration badge (e.g. '0-3s') at the top-right, and a clean text description card below with a tiny outline icon on the left (e.g. leaf, bowl, fire, drop, star icon). At the bottom, a prominent aesthetic spec footer detailing 'WARNA UTAMA' (color swatches), 'SUASANA', 'LINGKUNGAN', 'PENCAHAYAAN : Kuning hangat', dan 'FOKUS : Proses penyiapan'. Cute 3D animation style, warm cozy lighting, clean cartoon aesthetic. ${c.faceClause}.`;

const comic_grunge_storyboard = (c) => `A professional short story comic storyboard presentation sheet, vertical layout, heavily stylized with a textured grunged/dirty paper aesthetic. At the top header, a prominent red-brown banner showing 'STORYBOARD FILM PENDEK' and 'COMIC STORY' on the left, a giant bold comic title in center with 'PART ${c.pageNum}', a ripped cardboard note box showing 'KONSEP CERITA', and metadata labels showing 'GENRE : STORYBOARD', 'DURASI : ${c.durasiLabel}', 'ASPEK RASIO : ${c.rasioLabel}', 'GAYA VISUAL : GRUNGED ANIME STYLE'. The main content is a structured 3x3 (9-panel) comic grid displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each comic panel features a grunged hand-drawn anime/manga sketch illustration, a black square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at the top-left, a timestamp badge (e.g. '0:00 - 0:01') at the top-right, a sketchy Speech Bubble with cartoon text, a bottom-aligned 'TEKS OVERLAY: [Handwritten Bold Text]' block, and a bottom 'VOICE OVER: [Narration Quote]' black strip. At the bottom, a heavy grunged footer banner displaying 'CATATAN VISUAL', 'PALET WARNA' (with color swatch blocks), 'ELEMEN VISUAL' (with icons for coretan, stiker robek, noda cat, stempel), 'GAYA TEKS OVERLAY' (Handwritten, grunge highlight), and a giant yellow badge showing 'DURASI TOTAL: ${c.durasiLabel}'. Grungy manga sketch style, hand-drawn aesthetic, high-contrast shadows. ${c.faceClause}.`;

const character_design_turnaround = (c) => `A professional character and mecha design concept turnaround sheet, vertical layout sheet. At the top header, a bold red-and-white header banner reading 'STORYBOARD - CHARACTER DESIGN' and 'HENSHIN SEQUENCE SHEET' with the product/character title, an illustration of 'DRIVER BELT' or transformation device, and metadata boxes detailing 'THEME CONCEPT', 'HENSHIN CODE', 'GENRE', and 'ASPECT RATIO : ${c.rasioLabel}'. The main body is a structured 4x4 (16-panel) sequence grid displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each sequence panel contains a grunged hand-drawn anime sketch illustration showing parts attaching or turnaround views (Front/Back/Side View), a red square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at top-left, a bold scene title, description text, and diagram pointer callouts (e.g. 'FRONT WING', 'NOSE CONE', 'GLOWING VISOR'). At the bottom, a prominent technical breakdown spec footer detailing 'PARTS BREAKDOWN TO ARMOR' with individual parts slots, a 'SPEC DATA' table (Height, Weight, Punch/Kick Power, Max Speed), and a 'FINISHER' layout box. High-contrast sketch design, sharp typography, technical concept art style. ${c.faceClause}.`;

const cinematic_matrix_grid = (c) => `A professional B-Roll Film & TVC Storyboard Matrix Grid presentation sheet, vertical layout sheet. At the top header, a clean black-and-white header banner reading 'STORYBOARD - B-ROLL COMMERCIAL' and 'PART ${c.pageNum}' with a metadata line: 'DURATION : ${c.durasiLabel} | STYLE : CINEMATIC B-ROLL | ASPECT RATIO : ${c.rasioLabel}'. The main content is a structured 5-column matrix grid layout showing scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each grid panel contains a clean top header bar with numbered scene titles starting from scene ${c.startScene} up to ${c.endScene}, a 16:9 cinematic image panel, and a clean text metadata block underneath with 4 structured rows: 'CAMERA : [Shot Type]', 'FOCUS : [Focus Target]', 'ACTION : [Motion & Action]', and 'NOTES : [Lighting & Audio Notes]'. At the very bottom, a clean 4-box technical summary footer detailing 'VISUAL STYLE', 'MOOD & TONE', 'MUSIC & SOUND', and 'TOTAL DURATION & PLATFORM'. High-contrast director storyboard matrix grid, clean line borders, sharp typography, cinematic sketch studio lighting. ${c.faceClause}.`;

module.exports = {
  tiny_workers_miniature,
  comic_grunge_storyboard,
  character_design_turnaround,
  cinematic_matrix_grid,
};
