// Product-focused storyboard templates.
// Each template is `(c) => string`, where `c` is the context built by
// buildEnhancedPrompt: { startScene, endScene, pageNum, gridCount, gridLayout,
// timeString, finalPromptText, faceClause, durasiLabel, rasioLabel }.
// Note: the opening "A professional ... sheet" sentence is kept here (it is
// style-specific); buildEnhancedPrompt no longer prepends a duplicate (A2).
// Duration/aspect text uses c.durasiLabel / c.rasioLabel (A1/A3); no "--ar" (A3).

const cube_morph_product = (c) => `A professional 3D Cube Morph & Product Transition storyboard presentation sheet, vertical layout, clean dark-charcoal background. At the top header, a prominent gold-and-white header banner reading 'STORYBOARD - 3D CUBE MORPH TRANSITION' and the bold target product name in center with 'PART ${c.pageNum}', a 3D isometric cube wireframe diagram on the right, and metadata badges showing 'STYLE : 3D TRANSITION', 'ROTATION : MULTI-AXIS', 'ASPECT RATIO : ${c.rasioLabel}'. The main content is a structured 4-column comparison table layout displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}.

CRITICAL VISUAL RULES:
1. The table contains 4 columns:
   - Column 1: 'SCENE' containing a gold square scene number badge (${c.startScene}, ${c.startScene + 1}...) and time segment (e.g. '0:00 - 0:02').
   - Column 2: 'CUBE STATE' containing a widescreen 16:9 image panel detailing: A sleek mechanical cube resting statically on a clean white table surface, custom-designed with colors, branding decals, and surface details inspired directly by the target product from the reference image, smooth outer shell, small recessed button on top, warm ambient indoor lighting.
   - Column 3: 'TRANSITION DIRECTIVES' containing a clean dark-gray card box with written instructions: '[FIRST IMAGE PROMPT]: mechanical cube resting on table', '[SECOND IMAGE PROMPT]: mechanical cube unfolding automatically on table', and '[IMAGE TO VIDEO PROMPT]: panels splitting and reassembling into the final product view' in a clear, readable white sans-serif font.
   - Column 4: 'PRODUCT STATE' containing a widescreen 16:9 image panel detailing: Same POV angle, background and lighting as the previous image, a mechanical toy version of the uploaded reference target product standing on the same clean white table surface, keeping the exact original shape, proportions, and overall appearance of the real object so it remains instantly recognizable, but redesigned with subtle mechanical toy detailing, articulated panel lines, visible joints, tiny screws, layered mechanical parts, natural ambient indoor lighting.
2. Ensure there are gold arrows between Column 2 and Column 3 pointing to the right.
3. Every row must align perfectly, with clean table borders and high-contrast text boxes so that the written transition instructions are fully visible and readable on the canvas.

At the bottom, a technical rendering spec footer detailing 'TRANSITION CURVES', 'MOTION BLUR SPECS', '3D ENGINE RENDER', and 'AUDIO CLICK TIMING'. High-contrast design, clean borders, professional tech look. ${c.faceClause}.`;

const unboxing_cinematic_grid = (c) => `A professional product unboxing commercial storyboard sheet, vertical layout, clean dark-charcoal background. At the top header, a prominent dark banner reading 'STORYBOARD - UNBOXING' and the bold product title in center with 'PART ${c.pageNum}', and metadata fields showing 'DURASI TOTAL : ${c.durasiLabel}', 'JUMLAH SCENE : ${c.endScene}', 'ASPECT RATIO : ${c.rasioLabel}'. The main content is a structured 3x3 (9-shot) grid layout displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each grid panel displays a widescreen 16:9 unboxing photo, a red/black square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at the top-left, a red timestamp badge (e.g. '0.0 - 1.0 DETIK') at the top-right, and a structured metadata block below with 3 fields: 'VISUAL : [Description]', 'AKSI : [Action Description]', and 'KAMERA : [Camera Movement]'. At the bottom, a prominent 5-box technical summary footer detailing 'INFORMASI TEKNIS', 'CAMERA MOVEMENT' (with icons for WIDE SHOT, MEDIUM SHOT, CLOSE-UP, TOP-DOWN, LOW ANGLE, TRACKING, PUSH-IN, HANDHELD), 'VISUAL STYLE', 'NOTES FOR VIDEO GENERATION', and 'NEGATIVE PROMPT (HINDARI)'. Highly structured dark layout, sharp typography, professional product studio lighting. ${c.faceClause}.`;

const clean_step_card_grid = (c) => `A professional e-commerce product step-by-step usage storyboard poster, vertical layout, clean bright white background with a modern purple accent theme. At the top header, a clean white banner reading 'STORYBOARD – [PRODUCT TITLE] | Cara Pakai Mudah & Praktis' on the left, a purple rounded pill badge on the right reading 'DURASI : ${c.durasiLabel}', with thin gray separator lines. The main content is a structured 5x2 (10-panel) grid layout of clean rounded white card panels displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each card panel displays a widescreen 16:9 product usage photo, a purple square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at the top-left, a purple pill timestamp badge (e.g. '0:00-1s') at the top-right of the photo, and a text block below with a bold purple title (e.g. 'UNBOXING', 'LANGKAH 1') and a 1-2 sentence description of the action. At the bottom, a prominent dark purple footer banner reading '📢 PESAN UTAMA: Mudah digunakan, praktis & berkualitas tinggi!' on the left, and a brand official store logo on the right. High-contrast clean design, sharp sans-serif typography, bright studio lighting. ${c.faceClause}.`;

const premium_vertical_row = (c) => `A professional video storyboard presentation sheet, vertical layout, clean dark-charcoal background. At the top, there is a prominent header titled 'STORYBOARD PART ${c.pageNum}' in bold yellow and white sans-serif font, with a yellow-bordered details box showing 'DURASI : ${c.durasiLabel}', 'RASIO : ${c.rasioLabel}', 'LOKASI', and 'TEMA'. The main content is a vertical stack of widescreen video panels (rows) showing: ${c.finalPromptText}. Each row features a clean separation: on the left side, there is a dark column with a yellow square panel index number (e.g., '${c.startScene}', '${c.startScene + 1}') and shot name, description, and ASMR sound details in clean white and yellow text. On the right side is the widescreen panel image. At the very bottom, a horizontal yellow arrow transition bar showing 'TRANSISI / ENDING'. Highly structured, clean typography, high-contrast, cinematic lighting. ${c.faceClause}.`;

module.exports = {
  cube_morph_product,
  unboxing_cinematic_grid,
  clean_step_card_grid,
  premium_vertical_row,
};
