// Tutorial / table / infographic storyboard templates.
// See product.js header for the `c` context contract.

const recipe_cooking_table = (c) => `A professional recipe and cooking tutorial script table presentation sheet, vertical layout. At the top header, a prominent dark banner reading 'RECIPE STORYBOARD & ASMR TUTORIAL' and the bold food dish/recipe title in center with 'PART ${c.pageNum}', and metadata fields showing 'TOTAL TIME : ${c.durasiLabel}', 'SCENE COUNT : ${c.endScene}', 'ASPECT RATIO : ${c.rasioLabel}'. Below is a high-contrast 8-column storyboard table containing columns titled: 'TIME', 'SCENE', 'VISUAL DESCRIPTION', 'CAMERA', 'CONTINUITY', 'ASMR AUDIO', 'TRANSITION', and 'NOTES'. The table rows display scenes ${c.startScene} to ${c.endScene} showing: ${c.finalPromptText}. Column 1 shows time intervals (e.g. '00:00 - 00:01'). Column 2 shows the recipe preparation and cooking steps. Column 3 displays widescreen 16:9 cooking photos with a short visual action description. Column 4 shows camera shot angles (e.g. 'Close-up (Slow Push In)', 'Close-up (Macro)', 'Close-up (Top Angle)'). Column 5 describes continuity status. Column 6 specifies detailed recipe ASMR sounds (such as chopping, sizzling, baking, or boiling sounds matching the step description). Column 7 shows transition types (e.g. 'Match cut', 'Cut on action'). Column 8 displays technical notes. Professional food studio lighting, clean table borders, high contrast. ${c.faceClause}.`;

const diy_build_process = (c) => `A professional DIY build process and miniature crafting storyboard sheet, vertical layout stack. At the top header, a clean black-and-gold outline banner reading 'STORYBOARD – DIY BUILD PROCESS' with product fields showing 'DIY ITEM', 'STYLE : MINIATURE HOUSE', 'COMPLEXITY : SIMPLE'. The body features stacked scene rows for scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each row displays: on the left, a large gold scene number (${c.startScene < 10 ? '0' + c.startScene : c.startScene}, ${(c.startScene + 1) < 10 ? '0' + (c.startScene + 1) : (c.startScene + 1)}...) and timestamp (e.g. '0:00-0:02'); in the center, a widescreen 16:9 illustration of the miniature building step; on the right, a detailed technical metadata block with 6 rows: 'VISUAL SHOT', 'CAMERA MOVEMENT', 'ACTION', 'DETAIL FOCUS', 'SFX / ASMR', and 'TRANSITION'. At the bottom, a prominent footer detailing 'GLOBAL VISUAL PROMPT', 'GLOBAL ASMR PROMPT', a 'CAMERA DISTRIBUTION' pie chart, a 'SHOT LIST SUMMARY' table, and a 'SHOT HIGHLIGHTS' sub-footer bar. Elegant technical DIY design, gold/orange accents, clean dark borders. ${c.faceClause}.`;

const tiktok_script_table = (c) => `A professional TikTok/Reels commercial script table sheet presentation, vertical layout. At the top header, a prominent dark banner showing 'TIKTOK AD STORYBOARD (${c.durasiLabel})' and 'STORYBOARD PART ${c.pageNum}' with giant bold product title, tagline, 3 key benefit badges, and a prominent top-right hero product showcase box with a yellow starburst callout badge. Below the header is a high-contrast 5-column script table containing columns titled: 'SCENE', 'DURASI', 'VISUAL', 'VO / DIALOG', and 'TEXT ON SCREEN'. The table rows display scenes ${c.startScene} to ${c.endScene} showing: ${c.finalPromptText}. Column 1 shows bold scene index numbers (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) and scene role labels ('PROBLEM / HOOK', 'PRODUCT INTRODUCTION', 'TRANSFORMATION', 'PRODUCT DETAILS', 'RECOMMENDATION / CTA'). Column 2 shows duration (e.g. '2 SEC'). Column 3 displays high-fidelity visual panels with zoom-in circle badges. Column 4 displays voiceover narration quotes. Column 5 displays bold text-on-screen graphic overlays and red call-to-action button badges ('BELI SEKARANG!'). At the very bottom, a clean footer bar with feature icon badges. Highly structured social ad table layout, sharp typography, professional studio lighting. ${c.faceClause}.`;

const infographic_step_guide = (c) => `A professional step-by-step commercial infographic poster, vertical layout sheet. At the top header, a prominent title banner showing 'STORYBOARD PART ${c.pageNum}' in bold vibrant colors. The layout is organized into ${c.gridLayout} with prominent green/gold circular numbered badges starting from ${c.startScene} up to ${c.endScene} placed at the top-left of every panel indicating each step/scene in sequence. The panels show: ${c.finalPromptText}. Includes clear step-by-step tutorial text overlays, feature callouts, before-and-after curved transformation arrows, and product benefit checkmarks. At the very bottom, a clean footer bar with 3 circular feature icon badges ('Formula Extra Power', 'Natural Extraction', 'Safe & Tested'). Highly organized infographic poster layout, clean typography, vibrant studio lighting. ${c.faceClause}.`;

module.exports = {
  recipe_cooking_table,
  diy_build_process,
  tiktok_script_table,
  infographic_step_guide,
};
