// UGC (user-generated-content style) storyboard templates.
// See product.js header for the `c` context contract.

const ugc_overlay_card_grid = (c) => `A professional beauty/skincare UGC commercial script sheet, vertical layout. At the top header, a large bold product title banner with subtitle, and a top-right metadata card showing 'PLATFORM', 'DURASI : ${c.durasiLabel}', 'STYLE : BEAUTY INFLUENCER', 'HOOK STYLE : RELATABLE PROBLEM'. The body features stacked scene rows for scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each row displays on the left a 16:9 influencer visual panel with a dark 'SCENE [N]' badge at top-left, a timestamp badge at bottom-left ('00:00 - 00:02'), and a rounded white pill text overlay speech bubble badge at bottom-right of the image (e.g. 'Unboxing yuk! ✨'). On the right of each row is a clean metadata card box with 4 fields: 'SCENE TITLE', 'VISUAL', 'TEXT OVERLAY', and 'VOICE OVER'. At the bottom, 3 callout footer boxes: 'KENAPA HARUS [PRODUCT]?', 'INGAT!', and 'BELI SEKARANG!' with shopping cart icon. Clean aesthetic, soft studio lighting, sharp typography. ${c.faceClause}.`;

const ugc_overlay_dark_table = (c) => `A high-impact dark tech review UGC commercial script table sheet, vertical layout. At the top header, a heavy dark banner with bold product title, tagline, and top-right metadata box ('PLATFORM: YOUTUBE SHORTS', 'DURASI: ${c.durasiLabel}', 'GAYA: TECH REVIEW', 'HOOK STYLE: QUESTION'). Below is a gold-accented 4-column script table titled: 'SCENE', 'VISUAL & AKSI', 'TEXT OVERLAY', and 'VOICE OVER'. Rows display scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Column 1 shows giant gold scene numbers (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...), timestamp, and scene stage badges ('HOOK', 'INTRO', 'KELEBIHAN', 'DEMO FITUR', 'VERDICT + CTA'). Column 2 shows high-res influencer demonstration photos. Column 3 shows bold sticker-style graphic overlay text ('WORTH IT ATAU ENGGAK?', 'PERFORMA AJIB!', 'CHECK OUT SEKARANG!'). Column 4 shows voiceover dialogue. At the bottom, a dark product showcase footer banner titled 'CATATAN PRODUK'. High-contrast dark theme, bold typography, professional lighting. ${c.faceClause}.`;

const ugc_overlay_minimal_clean = (c) => `A clean aesthetic talking head UGC commercial script sheet, vertical layout. At the top header, a hero product image frame on the left, bold title & italic tagline in center, and top-right metadata row with icons ('Platform', 'Duration ${c.durasiLabel}', 'Style Talking Head', 'Hook Style Authority'). Below is a clean 6-column script table titled: 'SCENE', 'TIME', 'SCENE TITLE', 'VISUAL', 'TEXT OVERLAY', and 'VOICE OVER'. Rows display scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Column 1 displays circular scene badges (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) over presenter photos. Column 2 shows time interval ('00:00 - 00:02'). Column 3 shows scene title badges ('HOOK AWAL', 'ALASAN 1', 'RINGKASAN & CTA'). Column 4 shows visual description. Column 5 displays soft pastel rounded highlight overlay text badges ('3 Alasan Wajib Punya!', '1. Desain Elegant', 'Check Out Sekarang! 🛒'). Column 6 shows voiceover text. At the bottom, a clean lightbulb tip banner ('💡 TIPS: Gunakan tone ramah dan ekspresi natural'). Clean modern aesthetic, soft studio lighting. ${c.faceClause}.`;

const ugc_product_showcase_grid = (c) => `A professional UGC product showcase commercial storyboard sheet, vertical layout, clean bright white and pastel-colored background. At the top header, a clean pink/red accent banner reading 'STORYBOARD - UGC PRODUCT VIDEO' and the bold product title in center with 'PART ${c.pageNum}', and metadata fields showing 'DURASI TOTAL : ${c.durasiLabel}', 'JUMLAH SCENE : ${c.endScene}', 'ASPECT RATIO : ${c.rasioLabel}'. The main content is a structured 3x3 (9-shot) grid layout displaying scenes ${c.startScene} to ${c.endScene}: ${c.finalPromptText}. Each grid panel displays a widescreen 16:9 bright product B-roll photo, a pink/light-red square scene number badge (${c.startScene}, ${c.startScene + 1}, ${c.startScene + 2}...) at the top-left, a pink timestamp badge (e.g. '0.0 - 1.0 DETIK') at the top-right, and a structured metadata block below with 3 fields: 'VISUAL : [Description]', 'AKSI : [Action Description]', and 'KAMERA : [Camera Movement]'. At the bottom, a prominent 5-box technical summary footer detailing 'INFORMASI TEKNIS', 'CAMERA MOVEMENT' (with icons for WIDE SHOT, MEDIUM SHOT, CLOSE-UP, TOP-DOWN, PAN RIGHT, TILT DOWN, SLOW PUSH IN), 'VISUAL STYLE : Soft natural lighting, warm pastel tones, cozy aesthetic', 'NOTES FOR VIDEO GENERATION', and 'NEGATIVE PROMPT (HINDARI)'. Highly structured light layout, sharp typography, soft natural indoor lighting. ${c.faceClause}.`;

module.exports = {
  ugc_overlay_card_grid,
  ugc_overlay_dark_table,
  ugc_overlay_minimal_clean,
  ugc_product_showcase_grid,
};
